apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-app
  namespace: flux-system
spec:
  interval: 1m
  path: ./manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: nginx-source
  targetNamespace: default