apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: nginx-source
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/vanshika622/GitOps.git
  ref:
    branch: main